### ISSUE TITLE
Not updated to recent market information and a kudos to the creator

### ISSUE THREAD

**Issue by CodingProphecy** [rajivsarvepalli/warframe-trader#14]
Just wanted to let you know that I think this idea is a great idea and not something Ive found anywhere else. I wish the warframe market showed more details like you have on your site. However, when ever I checked the site after a extended break in 2023 I noticed that the site is no longer updated to the recent year of 2024? Is that due to any particular reason and one that I can help with?  Itd be a shame to have a project so detailed such as this one fall to the way side.

**Comment by rajivsarvepalli** [comment]
Data should be updated - looks like the job I have running failed as the API output changed slightly. Thanks for the heads up 👍

**Comment by CodingProphecy** [comment]
Great! I see it is now updated. Glad it was a simple fix. Thanks for being so quick with resolution!
